stage: sft
do_train: true
finetuning_type: freeze

model_name_or_path: /temp/models/Qwen3.5-0.8B
template: qwen2_vl
trust_remote_code: true

freeze_vision_tower: true
freeze_multi_modal_projector: false
freeze_trainable_layers: 8
freeze_trainable_modules: all

dataset_dir: data
dataset: merged_image_sft
cutoff_len: 4096
max_samples: null
overwrite_cache: true
preprocessing_num_workers: 8

output_dir: saves/qwen35-vl-small/freeze/merge
logging_steps: 10
save_steps: 200
plot_loss: true
overwrite_output_dir: true

per_device_train_batch_size: 6
gradient_accumulation_steps: 36
learning_rate: 1.0e-4
num_train_epochs: 3
lr_scheduler_type: cosine
warmup_ratio: 0.03
bf16: true